name: Go App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GO111MODULE: on

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Install Dependencies
      run: go mod download

    - name: Build
      run: go build -o app

    - name: Create .env file
      run: |
        echo "SECRETKEY=${{ secrets.SECRETKEY }}" > .env
        echo "DBUSER=${{ secrets.DBUSER }}" >> .env
        echo "DBPASSWORD=${{ secrets.DBPASSWORD }}" >> .env
        echo "DBHOST=${{ secrets.DBHOST }}" >> .env
        echo "DBPORT=${{ secrets.DBPORT }}" >> .env
        echo "DBNAME=${{ secrets.DBNAME }}" >> .env

    - name: Deploy to Ubuntu VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VMUSERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.VMSSHPORT }}
        script: |
          scp -o StrictHostKeyChecking=no -r . ${{ secrets.VMUSERNAME }}@${{ secrets.VMHOST }}:/path/to/remote/directory
          ssh -o StrictHostKeyChecking=no ${{ secrets.VMUSERNAME }}@${{ secrets.VMHOST }} "cd /path/to/remote/directory && ./app"
